version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ${POSTGRES_CONTAINER_NAME:-my_postgres}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_CONTAINER_NAME:-my_redis}
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - backend

  my_service:
    build:
      context: ./
    container_name: ${SERVICE_CONTAINER_NAME:-my_service}
    networks:
      - backend
    restart: always
    ports:
      - "${SERVICE_PORT:-4000}:4000"

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
